development:
  vkontakte:
    id: 3945912
    key: 1IjDVBxlO4BqZnWG8xK6
  facebook:
    id: 412366105530844
    key: e36de7b6021c7fc86073639a013d8e3f
    callback: 'http://localhost:3000/auth'
  admin_email: 'maksim.karganov@gmail.com'

test:
  vkontakte:
    id: 3945912
    key: 1IjDVBxlO4BqZnWG8xK6
  facebook:
    id: 412366105530844
    key: e36de7b6021c7fc86073639a013d8e3f
  admin_email: 'test@example.com'

production:
  vkontakte:
    id: 3945912
    key: 1IjDVBxlO4BqZnWG8xK6
  facebook:
    id: 412366105530844
    key: e36de7b6021c7fc86073639a013d8e3f
    callback: 'http://localhost:3000/auth'
  admin_email: 'test@example.com'
